### ISSUE TITLE
Schema export directory is not provided to the annotation processor so we cannot export the schema. You can either provide `room.schemaLocation` annotation processor argument OR set exportSchema to false.

### ISSUE THREAD

**Issue by cocpublic** [CankingApp/mvvmArch#2]
defaultConfig {
        applicationId "win.canking.mvvmarch"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

        //should add this
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation":
                                     "$projectDir/schemas".toString()]
            }
        }
    }

**Comment by CankingApp** [comment]
I have find this comment in Room source code.

>Whether the schema should be exported to the given folder when the
     * {@code room.schemaLocation} argument is set. 

I mean When not set "room.schemaLocation"，The project will not export schema no matter the exportSchema is true（same as exportSchema is false），and The compilation runs normally.

Well , I  had added the javaCompileOptions configure in my demo, and thanks your nice proposal. Please pull and retry.
