### ISSUE TITLE
关于框架中，关于网络请求和数据库读取数据合并成一个数据源的问题。

### ISSUE THREAD

**Issue by cornucopib** [CankingApp/mvvmArch#4]
我觉得框架中，不方便，不灵活的地方：
1.发起一个网络请求，是否代码量有点大；如果一个控制器下，有多个请求，感觉代码量很大
2.缓存策略，感觉不太灵活，利用数据源，来决定缓存策略，有点。。。。：
  result.addSource(dbSource, new Observer<ResultType>() {
            @Override
            public void onChanged(@Nullable ResultType resultType) {
                result.removeSource(dbSource);
                if (shouldFetch(resultType)) {
                    fetchFromNetwork(dbSource);
                } else {
                    result.addSource(dbSource, new Observer<ResultType>() {
                        @Override
                        public void onChanged(@Nullable ResultType resultType) {
                            result.setValue(Resource.success(resultType));
                        }
                    });
                }
            }
        });

**Comment by CankingApp** [comment]
个人理解：
1，底层逻辑的封装（比一般逻辑的直接请求代码是大点），是为了上层（业务层）的简洁调用，用接口隔绝了具体实现，也为项目的升级迭代提供基础能力；控制器在具体项目中，肯定是按照模块或业务等实现为多个的，Demo中只是个小例子。
2，Demo中的缓存只是一种实现方式，的确在实际工程中不这么用，这里主要是为了讲解整体框架临时作的一种方案。

^ ^ 🙏

**Comment by Vector-SMG** [comment]
个人觉得，理想中的样子：应该仿照okhttp或者picasso调用的方式，代码量大是可以接受的，但是要对使用者简化调用方式，将整个流程变化的部分，由使用者来配置，比如：缓存策略，数据的泛型等。^ ^
